version: '3.8'
services:
  chat-service:
    build: ./chat_service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI}

  room-service:
    build: ./room_service
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=${MONGO_URI}
