version: '3.8'
services:
  chat-service:
    build: ./backend/chat_service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI}

  room-service:
    build: ./backend/room_service
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=${MONGO_URI}
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ROOM_API_URL=http://localhost:8083
      - REACT_APP_API_URL = http://localhost:8082
